futures_exchange_dict = {
    '20号胶': '上海期货交易所',
    'PTA': '郑州商品交易所',
    '丁二烯橡胶': '上海期货交易所',
    '不锈钢': '上海期货交易所',
    '乙二醇': '大连商品交易所',
    '低硫燃料油': '上海期货交易所',
    '动力煤': '郑州商品交易所',
    '原木': '大连商品交易所',
    '原油': '上海期货交易所',
    '对二甲苯': '郑州商品交易所',
    '尿素': '郑州商品交易所',
    '工业硅': '广州期货交易所',
    '强麦': '郑州商品交易所',
    '早籼稻': '郑州商品交易所',
    '晚籼稻': '郑州商品交易所',
    '普麦': '郑州商品交易所',
    '棉纱': '郑州商品交易所',
    '棉花': '郑州商品交易所',
    '棕榈油': '大连商品交易所',
    '橡胶': '上海期货交易所',
    '氧化铝': '上海期货交易所',
    '沥青': '上海期货交易所',
    '油菜籽': '郑州商品交易所',
    '液化石油气': '大连商品交易所',
    '烧碱': '郑州商品交易所',
    '热轧卷板': '上海期货交易所',
    '焦炭': '大连商品交易所',
    '焦煤': '大连商品交易所',
    '燃料油': '上海期货交易所',
    '玉米': '大连商品交易所',
    '玉米淀粉': '大连商品交易所',
    '玻璃': '郑州商品交易所',
    '瓶片': '郑州商品交易所',
    '生猪': '大连商品交易所',
    '甲醇': '郑州商品交易所',
    '白糖': '郑州商品交易所',
    '白银': '上海期货交易所',
    '短纤': '郑州商品交易所',
    '硅铁': '郑州商品交易所',
    '硬麦': '郑州商品交易所',
    '碳酸锂': '广州期货交易所',
    '粳稻谷': '郑州商品交易所',
    '粳米': '大连商品交易所',
    '红枣': '郑州商品交易所',
    '纤维板': '大连商品交易所',
    '纯碱': '郑州商品交易所',
    '纸浆': '上海期货交易所',
    '线材': '上海期货交易所',
    '聚丙烯': '大连商品交易所',
    '聚乙烯': '大连商品交易所',
    '聚氯乙烯': '大连商品交易所',
    '胶合板': '大连商品交易所',
    '花生': '郑州商品交易所',
    '苯乙烯': '大连商品交易所',
    '苹果': '郑州商品交易所',
    '菜籽粕': '郑州商品交易所',
    '螺纹钢': '上海期货交易所',
    '豆一': '大连商品交易所',
    '豆二': '大连商品交易所',
    '豆油': '大连商品交易所',
    '豆粕': '大连商品交易所',
    '铁矿石': '大连商品交易所',
    '铅': '上海期货交易所',
    '铜': '上海期货交易所',
    '铝': '上海期货交易所',
    '锌': '上海期货交易所',
    '锡': '上海期货交易所',
    '锰硅': '郑州商品交易所',
    '镍': '上海期货交易所',
    '阴极铜': '上海期货交易所',
    '鸡蛋': '大连商品交易所',
    '黄金': '上海期货交易所',
    '多晶硅': '广州期货交易所',
    '欧线': '上海期货交易所',
    '菜籽油': '郑州商品交易所'
}

futures_english_dict = {
    '甲醇': 'Methanol',
    '燃料油': 'Fuel Oil',
    '白糖': 'White Sugar',
    '强麦': 'Strong Wheat',
    '普麦': 'Common Wheat',
    '豆一': 'No.1 Soybean',
    '豆二': 'No.2 Soybean',
    '玉米': 'Corn',
    '菜籽油': 'Rapeseed Oil',
    '菜籽粕': 'Rapeseed Meal',
    '菜籽': 'Rapeseed',
    '豆粕': 'Soybean Meal',
    '棕榈油': 'Palm Olein',
    '豆油': 'Soybean Oil',
    '棉花': 'Cotton',
    '玻璃': 'Flat Glass',
    'PTA': 'PTA',
    '天然橡胶': 'Natural Rubber',
    'LLDPE': 'LLDPE',
    'PVC': 'PVC',
    '焦炭': 'Coke',
    '焦煤': 'Coking Coal',
    '铝': 'Aluminum',
    '黄金': 'Gold',
    '铜': 'Copper',
    '铅': 'Lead',
    '螺纹钢': 'Rebar',
    '线材': 'Wire Rod',
    '锌': 'Zinc',
    '白银': 'Silver',
    '原木': None,
    '对二甲苯': None,
    '瓶片': None,
    '硬麦': None,
    '粳稻谷': None,
    '多晶硅': None,
}

futures_english_dict2 = {
    '20号胶': 'Rubber 20',
    'PTA': 'PTA',
    '丁二烯橡胶': 'Butadiene Rubber',
    '不锈钢': 'Stainless Steel',
    '乙二醇': 'Ethylene Glycol',
    '低硫燃料油': 'Low Sulfur Fuel Oil',
    '动力煤': 'Thermal Coal',
    '原木': 'Logs',
    '原油': 'Crude Oil',
    '对二甲苯': 'Paraxylene',
    '尿素': 'Urea',
    '工业硅': 'Industrial Silicon',
    '强麦': 'Strong Wheat',
    '早籼稻': 'Early Long-Grain Rice',
    '晚籼稻': 'Late Long-Grain Rice',
    '普麦': 'Common Wheat',
    '棉纱': 'Cotton Yarn',
    '棉花': 'Cotton',
    '棕榈油': 'Palm Oil',
    '橡胶': 'Rubber',
    '氧化铝': 'Alumina',
    '沥青': 'Asphalt',
    '油菜籽': 'Rapeseed',
    '液化石油气': 'Liquefied Petroleum Gas (LPG)',
    '烧碱': 'Caustic Soda',
    '热轧卷板': 'Hot Rolled Coil',
    '焦炭': 'Coke',
    '焦煤': 'Coking Coal',
    '燃料油': 'Fuel Oil',
    '玉米': 'Corn',
    '玉米淀粉': 'Corn Starch',
    '玻璃': 'Glass',
    '瓶片': 'Bottle-Grade PET Chips',
    '生猪': 'Live Hog',
    '甲醇': 'Methanol',
    '白糖': 'White Sugar',
    '白银': 'Silver',
    '短纤': 'Short Staple Fiber',
    '硅铁': 'Ferrosilicon',
    '硬麦': 'Hard Wheat',
    '碳酸锂': 'Lithium Carbonate',
    '粳稻谷': 'Japonica Rice',
    '粳米': 'Japonica Rice',
    '红枣': 'Red Dates',
    '纤维板': 'Fiberboard',
    '纯碱': 'Soda Ash',
    '纸浆': 'Pulp',
    '线材': 'Wire Rod',
    '聚丙烯': 'Polypropylene (PP)',
    '聚乙烯': 'Polyethylene (PE)',
    '聚氯乙烯': 'Polyvinyl Chloride (PVC)',
    '胶合板': 'Plywood',
    '花生': 'Peanuts',
    '苯乙烯': 'Styrene',
    '苹果': 'Apples',
    '菜籽粕': 'Rapeseed Meal',
    '螺纹钢': 'Rebar',
    '豆一': 'No.1 Soybean',
    '豆二': 'No.2 Soybean',
    '豆油': 'Soybean Oil',
    '豆粕': 'Soybean Meal',
    '铁矿石': 'Iron Ore',
    '铅': 'Lead',
    '铜': 'Copper',
    '铝': 'Aluminum',
    '锌': 'Zinc',
    '锡': 'Tin',
    '锰硅': 'Silicon Manganese',
    '镍': 'Nickel',
    '阴极铜': 'Cathode Copper',
    '鸡蛋': 'Eggs',
    '黄金': 'Gold',
    '多晶硅': 'Polysilicon',
    '欧线': 'Containerized Freight Index (Europe Route) Futures',
    '菜籽油': 'Rapeseed Oil'
}


future_and_acro = {
    "豆一": "A",
    "白银": "AG",
    "铝": "AL",
    "苹果": "AP",
    "黄金": "AU",
    "豆二": "B",
    "胶合板": "BB",
    "阴极铜": "BC",
    "沥青": "BU",
    "玉米": "C",
    "棉花": "CF",
    "红枣": "CJ",
    "玉米淀粉": "CS",
    "铜": "CU",
    "棉纱": "CY",
    "苯乙烯": "EB",
    "乙二醇": "EG",
    "纤维板": "FB",
    "玻璃": "FG",
    "燃料油": "FU",
    "热轧卷板": "HC",
    "铁矿石": "I",
    "焦炭": "J",
    "鸡蛋": "JD",
    "焦煤": "JM",
    "粳稻谷": "JR",
    "聚乙烯": "L",
    "生猪": "LH",
    "晚籼稻": "LR",
    "低硫燃料油": "LU",
    "豆粕": "M",
    "甲醇": "MA",
    "镍": "NI",
    "20号胶": "NR",
    "菜籽油": "OI",
    "棕榈油": "P",
    "铅": "PB",
    "短纤": "PF",
    "液化石油气": "PG",
    "花生": "PK",
    "普麦": "PM",
    "聚丙烯": "PP",
    "螺纹钢": "RB",
    "早籼稻": "RI",
    "菜籽粕": "RM",
    "粳米": "RR",
    "油菜籽": "RS",
    "橡胶": "RU",
    "纯碱": "SA",
    "原油": "SC",
    "硅铁": "SF",
    "锰硅": "SM",
    "锡": "SN",
    "纸浆": "SP",
    "白糖": "SR",
    "不锈钢": "SS",
    "PTA": "TA",
    "尿素": "UR",
    "聚氯乙烯": "V",
    "强麦": "WH",
    "线材": "WR",
    "硬麦": "WT",
    "豆油": "Y",
    "动力煤": "ZC",
    "锌": "ZN",
    "丁二烯橡胶": "A1",
    "原木": "A2",
    "多晶硅": "A3",
    "对二甲苯": "A4",
    "工业硅": "A5",
    "欧线": "A6",
    "氧化铝": "A7",
    "烧碱": "A8",
    "瓶片": "A9",
    "碳酸锂": "A10",

}

duplicate_dict = {
    "对二甲苯": "二甲苯",
    "油菜籽": "菜籽",
    "燃料油": "燃油",
    "瓶片": "瓶级聚酯切片",
    "甲醇": "郑醇",
    "聚丙烯": "PP",
    "聚乙烯": "塑料",
    "聚氯乙烯": "PVC",
    "菜籽粕": "菜粕",
    "阴极铜": "国际铜",
    "菜籽油": "菜油",
    "乙二醇": "EG",
    "苯乙烯": "EB"
}

duplicate_dict2 = {
    "对二甲苯": "二甲苯",

}